name: alertadengue
channels:
  - conda-forge
  - defaults
dependencies:
- django=3.0.7
- django-bootstrap4
- geojson
- gunicorn
- numpy
- pandas=1.1.5 #issue#385
- pip=19.3
- python=3.7
- python-dotenv
- pytz
- psycopg2
- sqlalchemy
- python-memcached
- django-makemessages-xgettext
- mock
- dbfread
- dj-database-url
- django-chunked-upload=1.1.3
- docker-compose==1.27.4
- celery
- dj-static
- pyproj
- gdal=2.4.2
- fiona
- rasterio
- boto3
- geopy
- geopandas
- sh
- ipython
- sqlparse
- plotly=4.0.0
- BeautifulSoup4
- make
- pip:
    - django-leaflet==0.26.0
    - django-maintenance-mode
    - ibis_framework==1.3.0
