name: alertadengue
channels:
  - conda-forge
  - defaults
dependencies:
- django>=2,<3
- django-bootstrap4
- django-leaflet==0.26.0
- geojson
- gunicorn
- numpy
- pandas
- pip=19.3
- python=3.7
- python-dotenv
- pytz
- psycopg2
- sqlalchemy
- python-memcached
- django-makemessages-xgettext
- mock
- dbfread
- dj-database-url
- django-chunked-upload=1.1.3
- docker-compose
- celery
- dj-static
- pyproj
- gdal=2.4.2
- fiona
- rasterio
- boto3
- geopy
- geopandas
- sh
- ipython
- sqlparse
- plotly=4.0.0
- BeautifulSoup4
- setuptools=41.5.1 # TODO: remove this when django 3 is used
- pip:
    - django-leaflet==0.26.0
    